# Generated by Django 4.0.4 on 2022-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_post_phonenumber_post_read_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
    ]
