# Generated by Django 4.0.4 on 2022-05-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_post_head_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_book',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='phonenumber',
            field=models.TextField(),
        ),
    ]
